Feature/gallery
Piotrek92PL/ICP-Team-Project pull request #14
Opened 2022-12-17 19:49 UTC by PawelMajewskiPolska

2022-12-17 19:56 UTC, Piotrek92PL commented on src/sass/main.css
>  }/*# sourceMappingURL=main.css.map */
Do skasowania

2022-12-18 15:02 UTC, mykolakovalskyi commented on src/partials/gallery.html
> +          media="(min-width: 1200px)"
Punkt przecięcia 1280px

2022-12-18 15:08 UTC, mykolakovalskyi requested changes

2022-12-18 15:08 UTC, mykolakovalskyi commented on src/partials/gallery.html
> +          media="(min-width: 1200px)"
Punkt przecięcia 1280px

2022-12-18 15:08 UTC, mykolakovalskyi commented on src/sass/_gallery.scss
> +  @media screen and (min-width: 1200px) {
Punkt przecięcia 1280 px

2022-12-18 15:08 UTC, mykolakovalskyi commented on src/sass/_gallery.scss
> +  background-image: linear-gradient(to bottom, #fff5f6 39.77%, #ffffff 39.77%, #ffffff 100%);
#ffffff 100% nie jest obowiązkowe 😅

2022-12-18 15:08 UTC, mykolakovalskyi commented on src/sass/_gallery.scss
> +    max-width: 1200px;
1280 px

2022-12-18 15:08 UTC, mykolakovalskyi commented on src/sass/_gallery.scss
> +    max-width: 1280px;
Punkt przecięcia 1280px

2022-12-19 22:48 UTC, mykolakovalskyi approved these changes

2022-12-19 22:49 UTC, merged