Feature/about
Piotrek92PL/ICP-Team-Project pull request #16
Opened 2022-12-17 21:36 UTC by lubkepatryk

2022-12-18 09:45 UTC, Piotrek92PL submitted a review, later dismissed

2022-12-18 09:45 UTC, Piotrek92PL commented on package.json
> +  "homepage": "https://lubkepatryk.github.io/ICP-Team-Project",
Tego nie powinno tu być

2022-12-18 09:45 UTC, Piotrek92PL commented on package.json
> -  "homepage": "https://Piotrek92PL.github.io/ICP-Team-Project",
To zostawiamy w spokoju :D

2022-12-18 09:45 UTC, Piotrek92PL commented on src/partials/about.html
> +          ././images/milkandcow-desktop-x1.png 516w
brakuje zdjęć x2 pod retine

2022-12-18 15:21 UTC, mykolakovalskyi requested changes

2022-12-18 15:21 UTC, mykolakovalskyi commented on src/partials/about.html
> +        sizes="(min-width: 320px) 280px, (min-width: 772px) 340px, (min-width: 1280px) 516px, 100vw"
100vw nie może być domyślną wartością, tu musi być wartość dla mobile first

2022-12-19 17:06 UTC, lubkepatryk commented on package.json
> +  "homepage": "https://lubkepatryk.github.io/ICP-Team-Project",
zmieniłem z powrotem na Piotrek92PL

2022-12-19 17:23 UTC, lubkepatryk commented on src/partials/about.html
> +          ././images/milkandcow-desktop-x1.png 516w
już dodałem

2022-12-19 17:23 UTC, lubkepatryk commented on src/partials/about.html
> +        sizes="(min-width: 320px) 280px, (min-width: 772px) 340px, (min-width: 1280px) 516px, 100vw"
usunąłem 100vw

2022-12-19 19:20 UTC, Piotrek92PL commented on src/sass/_about.css
> +.about{background-color:var(--rose-white);max-width:var(--mobile-width);padding-top:125px;padding-bottom:39px;margin:0 auto}@media screen and (min-width: 768px){.about{max-width:var(--tablet-width);p
Ten plik nie jest w ogóle potrzebny :) korzystamy tylko z _about.scss bo importujemy je do maina, a tego nawet nigdzie nie podłączymy :)

2022-12-19 19:33 UTC, lubkepatryk commented on src/sass/_about.css
> +.about{background-color:var(--rose-white);max-width:var(--mobile-width);padding-top:125px;padding-bottom:39px;margin:0 auto}@media screen and (min-width: 768px){.about{max-width:var(--tablet-width);p
tak, ten plik jest niepotrzebny, ale ciągle mi się generuje jak odpalam VSC, zapomniałem go usunąć przed zarequestowaniem

2022-12-19 22:41 UTC, mykolakovalskyi approved these changes

2022-12-19 22:42 UTC, merged